### ISSUE TITLE
Show the filled character instead of an outline

### ISSUE THREAD

**Issue by ehdwns980416** [chill-chinese/stroke-order-animator#27]
How to show users a preview before showing the stroke animation?

![image](https://user-images.githubusercontent.com/26425092/222441268-3a971ca5-3c72-43d7-9905-1601d45fd07c.png)

**Comment by Mr-Pepe** [comment]
A preview of what exactly?

**Comment by ehdwns980416** [comment]
@Mr-Pepe I want to show the shape of the letter in a filled color, not an outline.

**Comment by Mr-Pepe** [comment]
Got it. Do you want to still have an additional outline? The feature would be a nice one but I don't think that I'll find the time to implement it anytime soon. For the time being, you could maybe draw the same character twice, with one drawing onto the other.

**Comment by ehdwns980416** [comment]
That's great! I can use `showFullCharacter()` for the base character, right?

**Comment by Mr-Pepe** [comment]
Yes, that should work. You can give it the color you want by setting the `strokeColor`.

**Comment by Mr-Pepe** [comment]
@ehdwns980416 I don't know if this is still relevant to you, but the feature is available in version 3.2.0 :slightly_smiling_face:  

Simply set `showBackground: true` when creating the `StrokeOrderAnimationController` or call `setShowBackground(true)` on it. You can set the color via `backgroundColor`.
