### ISSUE TITLE
Have all the features of the hanzi-writer library been implemented?

### ISSUE THREAD

**Issue by giantss** [chill-chinese/stroke-order-animator#94]
First of all, thank you for providing such a great flutter plugin.

Does this library already implement all the functions of the [hanzi-writer](https://github.com/chanind/hanzi-writer) library?

**Comment by giantss** [comment]
I found a problem when using the demo. How can I display the font when `showOutline = false`, like the picture below.
<img width="290" alt="image" src="https://github.com/user-attachments/assets/422b4d8d-d706-44e1-81cc-7a7ea88ef830">

**Comment by Mr-Pepe** [comment]
> First of all, thank you for providing such a great flutter plugin.

Glad you like it :relaxed: 

> Does this library already implement all the functions of the [hanzi-writer](https://github.com/chanind/hanzi-writer) library?

Definitely not. I have just implemented the stuff I need over at [Chill Chinese](https://app.chill-chinese.com) and will continue extending this library as necessary.

> How can I display the font when showOutline = false, like the picture below.

See https://github.com/chill-chinese/stroke-order-animator/issues/27#issuecomment-2151672846.

Let me know if you have more questions.

**Comment by giantss** [comment]
Great! I got your reply so quickly. I feel it is very good after testing it.

**Comment by giantss** [comment]
It would be great if there was an attribute to control the display and hiding of the nine-square grid, because it is very important to learn to write Chinese characters in the nine-square grid in China. Like the picture below.

<img width="120" alt="image" src="https://github.com/user-attachments/assets/384e2967-0853-4c24-8ca1-3a2b0e2b0963">

**Comment by Mr-Pepe** [comment]
See https://github.com/chill-chinese/stroke-order-animator/issues/5. I'll post an explanation there why I think that feature shouldn't be part of the library.

**Comment by Mr-Pepe** [comment]
See https://github.com/chill-chinese/stroke-order-animator/issues/5#issuecomment-2296117563.

**Comment by giantss** [comment]
Okay, there is actually only one standard nine-square grid, which is the one you posted.
![image](https://github.com/user-attachments/assets/232d682b-a4c9-4543-bb52-d1b30745ce15)

**Comment by Mr-Pepe** [comment]
You are confusing me a bit because that one doesn't actually have nine squares, but if you are happy, I'm happy :smile:

**Comment by giantss** [comment]
Sorry, I made a slip of the tongue. In ancient times, Chinese people often used the nine-square grid. The grid on the top is the "米" grid, which is basically used in learning Chinese writing in modern China.
