### ISSUE TITLE
The UI does not change after the second word is loaded

### ISSUE THREAD

**Issue by giantss** [chill-chinese/stroke-order-animator#96]
<img width="630" alt="image" src="https://github.com/user-attachments/assets/9086a63e-733e-431b-93ea-91518554c48e">

In the figure, the animation of the first character is played and the user finishes drawing. When the second character is loaded using _loadStrokeOrder again, the character in the nine-square grid does not change to the second character (the same logic as the first character). This may not be a bug. How can I switch to the second word normally? Most of the code I use comes from the demo code you provided.

**Comment by Mr-Pepe** [comment]
I don't fully understand what you are trying to achieve. It seems that you want to automatically switch to the second character after the first one finishes animating. But you also mention the user drawing something, so maybe you are talking about quiz mode? If you could provide a minimal example that reproduces your issue, I might be able to help.

You can insert `print` at different places in your code and verify that it does what you think it does. Does the second stroke order get loaded correctly after the first character finishes? If you have a stateful widget, do you use `setState` to rebuild the widget tree with the new stroke order?

**Comment by Mr-Pepe** [comment]
That function doesn't get executed when you want your program to switch to the second character, right? If you add a `print("...")` before `return Container` that doesn't get printed for the second character, right? 

You need to somehow trigger a rebuild of the widget when you have loaded the stroke order. The example code uses a `FutureBuilder` for that but any state management solution will work.

**Comment by giantss** [comment]
This function (buildStrokeOrderAnimation) should be executed.
I debugged it and found that this function will be executed when the program switches to the second character. In theory, the UI of the second character should have been refreshed, but the UI still looks like the first character.

**Comment by giantss** [comment]
Thank you for helping me analyze the problem. I solved this problem. It was my code problem. I forgot to assign the value of `_loadStrokeOrder` to `animationController` the second time.
